### ISSUE TITLE
Cursor should change to pointer when hovering on "View Open/Closed"

### ISSUE THREAD

**Issue by ceceliacreates** [Replayio/gotbugs#16]
https://app.replay.io/recording/filter-styling--1d8d37c9-7f54-40ef-a2cc-20319dde03e7

**Comment by jasonLaster** [comment]
gosh - i'd love to fix this gecko-dev issue
https://github.com/RecordReplay/gecko-dev/issues/568

cc @markerikson now that you've got gecko-dev spun up, interested in being a gecko-dev hacker for a day?
